apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    cloudcontrol.enabled: "true"
    cloudcontrol.index: "1"
    LAUNCHPAD_ENABLE: "true"
    LAUNCHPAD_COLOR: LIGHT_BLUE
    LAUNCHPAD_ROW: "6"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: default
spec:
  backend:
    serviceName: nginx
    servicePort: 80
