apiVersion: v1
kind: Secret
metadata:
  name: twitter-secret
type: Opaque
data:
  api-key: VE1iazduMlJTdHZXNHd0V0VpZnFmTHlsaA==
  api-secret: TXlZckdLdmdJYTZxbWJSajhiZlcwVTBINVVhY0Q2VHZKWE5QQ0poZ3ZscmZNZWFaQ2I=
