apiVersion: v1
kind: Service
metadata:
  name: zwitscher-service
  labels:
    zwitscher: service
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8080
  selector:
    zwitscher: service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-service
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        zwitscher: service
        LAUNCHPAD_ENABLE: "true"
        LAUNCHPAD_COLOR: LIGHT_GREEN
        LAUNCHPAD_ROW: "1"
    spec:
      containers:
      - name: zwitscher-service
        image: "hitchhikersguide/zwitscher-service:1.0.1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8080
          timeoutSeconds: 30
        env:
        - name: CONSUL_HOST
          value: zwitscher-consul
