################################################################
# Global configuration
################################################################

# Backend-specific constraint
# [consulCatalog]
#   endpoint = 127.0.0.1:8500
#   constraints = ["tag==api"]


################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]
address = ":8888"

# Enable more detailed statistics
[web.statistics]
  RecentErrors = 10


################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend
[consulCatalog]

# Consul server endpoint
endpoint = "192.168.99.100:8500"

# Default domain used (Optional)
domain = "consul.localhost"

# Prefix for Consul catalog tags (Optional)
prefix = "traefik"
