version: '2'

services:
  zwitscher-consul:
    image: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - zwitscher-net

  zwitscher-traefik:
    image: traefik
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - "8888:8888"
      - "80:80"
    depends_on:
      - zwitscher-consul
    links:
      - zwitscher-consul
    networks:
      - zwitscher-net

  zwitscher-service:
    image: zwitscher-service:1.1.1
    environment:
      - CONSUL_HOST=zwitscher-consul
      - CONSUL_PORT=8500
      - TWITTER_APP_ID=${TWITTER_APP_ID}
      - TWITTER_APP_SECRET=${TWITTER_APP_SECRET}
    depends_on:
      - zwitscher-consul
    links:
      - zwitscher-consul
    ports:
      - "8080:8080"
    networks:
      - zwitscher-net

  zwitscher-board:
    image: zwitscher-board:1.0.1
    environment:
      - CONSUL_HOST=zwitscher-consul
      - CONSUL_PORT=8500
    depends_on:
      - zwitscher-consul
    links:
      - zwitscher-consul
    ports:
      - "8081:8081"
    networks:
      - zwitscher-net

networks:
  zwitscher-net:
    driver: bridge
