##
## This Prometheus config must be mounted into your container inside Kubernetes.
## The containing folder must therefore be available in the Kubernetes host machine.
## This can be tricky when running Minikube inside a VM.
## An easy work around is to copy the containing folder into your User directory
## and set the hostPath property of the volume in k8s-zwitscher-prometheus.yml accordingly.
## The user folder is automatically mounted into Minikube under /c/Users/<username>
##

global:
  scrape_interval: 5s

  external_labels:
      monitor: 'zwitscher-monitor'
  
scrape_configs:
  - job_name: 'consul'

    consul_sd_configs:
    - server: zwitscher-consul:8500

    relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         ',(production|canary),'
      target_label:  'group'
      replacement:   '$1'