##
## This Prometheus config must be mounted into your container inside Kubernetes.
## The containing folder must therefore be available in the Kubernetes host machine.
## This can be tricky when running Minikube inside a VM.
## An easy work around is to copy the containing folder into your User directory
## and set the hostPath property of the volume in k8s-zwitscher-prometheus.yml accordingly.
## The user folder is automatically mounted into Minikube under /c/Users/<username>
##

global:
  scrape_interval: 5s

  external_labels:
      monitor: 'zwitscher-monitor'
  
scrape_configs:
  - job_name: 'zwitscher-service'

    consul_sd_configs:
    - server: zwitscher-consul:8500

    relabel_configs:

    #Keep only the zwitscher-service endpoints
    - source_labels: ['__meta_consul_service']
      regex:         '(.*zwitscher-service.*)'
      action:        'keep'

    #Use the service name as job name
    - source_labels: ['__meta_consul_service']
      target_label:  'job'

    #Use service instance id as instance name
    - source_labels: ['__meta_consul_service_id']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'

    #Use the specified path as metrics target
    - source_labels: ['__metrics_path__']
      regex:         '(.*)'
      target_label:  '__metrics_path__'
      replacement:   '/tweets'